### ISSUE TITLE
What is c?

### ISSUE THREAD

**Issue by lbassin** [agranjeon/gitplan#2]
I like you tool but I don't understand, what is c?

https://github.com/agranjeon/gitplan/blob/462059ae9b3ec2dfa902b2ab60a9ab348e0fe369/consume.go#L44

**Comment by agranjeon** [comment]
Please format your issue according to our guidelines

**Comment by lbassin** [comment]
I don't see any guideline

**Comment by agranjeon** [comment]
Please, use one of the Issue Template next time 👍🏻

**Comment by lbassin** [comment]
sorry
